export function createPlayerControllerApi({
  playerProject,
  material,
  modelScene,
  viewerSettings,
  outlineObjects,
  blinkSelectionEnabled,
  shaderOutlineObjects,
  shaderOutlineStyle,
  setOutlineObjects,
  setSelectedObject,
  cameraRef,
  controlsRef,
  focusTargetRef,
  freePlay,
  selectedObject,
  transformMode,
  objectList,
  focusObject,
  makePlayerXrayExcept,
  resetPlayerObjectXray,
  setObjectListSelectedObject,
  playerChapter,
  handleSelectChapterCameraView,
  playerAnimation,
  handleSelectObjectFromPlayer,
  handleDoubleClickObjectFromPlayer,
  clearPlayerSelection,
  handleModelLoaded,
  captureInitialCameraState,
  showAnnotations,
  activeFlow,
  flowPlaying,
  setFlowPlaying,
  flowPlaybackKey,
  activeChapterFlows,
  chapterFlowPlaybackKey,
  handleChapterFlowComplete,
  playerProcedure,
  playerSpeech,
  getChapterFlowAssignments,
  activeChapterFlowIds,
  playChapterFlow,
  stopChapterFlows,
  flows,
  activeFlowId,
  playFlow,
  stopFlow,
  freePlayMenu,
  cutEnabled,
  playerFreePlay,
  togglePlayerPullApart,
  hideSelectedPlayerObject,
  resetAllPlayerView,
  hideAllObjects,
  cutAxis,
  cutValue,
  cutValues,
  cutRanges,
  cutMin,
  cutMax,
  setCutValue,
  activeMenu,
  activeChapterId,
  visibleChapters,
  handleSelectChapter,
  clearActiveChapter,
  setViewerSettings,
  applyPlayerShaderMode,
  setPlayerMetalness,
  setPlayerRoughness,
  updatePlayerEnvIntensity,
  setShowAnnotations,
  resetPlayerView,
  setFreePlay,
  setFreePlayMenu,
  setActiveMenu,
  setShowInfoPanel,
  setCutEnabled,
  showInfoPanel,
}) {
  return {
    status: {
      isLoadingProject: playerProject.isLoadingProject,
      isSceneReady: playerProject.isSceneReady,
      loadError: playerProject.loadError,
    },

    scene: {
      material,
      modelScene,
      viewerSettings,
      outlineObjects,
      blinkSelectionEnabled,
      shaderOutlineObjects,
      shaderOutlineStyle,
      setOutlineObjects,
      setSelectedObject,
      cameraRef,
      controlsRef,
      focusTargetRef,
      freePlay,
      selectedObject,
      transformMode,
      objectList,
      focusObject,
      makeXrayExcept: makePlayerXrayExcept,
      resetXray: resetPlayerObjectXray,
      setObjectListSelectedObject,
      activeChapter: playerChapter.activeChapter,
      selectedAnimations: playerAnimation.selectedAnimations,
      animationCommand: playerAnimation.animationCommand,
      handleSelectObjectFromPlayer,
      handleDoubleClickObjectFromPlayer,
      clearPlayerSelection,
      handleModelLoaded,
      captureInitialCameraState,
      onSceneReady: playerProject.notifySceneReady,
      setAnimations: playerAnimation.setAnimations,
      showAnnotations,
      activeFlow,
      flowPlaying,
      flowPlaybackKey,
      activeChapterFlows,
      chapterFlowPlaybackKey,
      onChapterFlowComplete: handleChapterFlowComplete,
      onFlowComplete: () => {
        if (!activeFlow?.settings?.repeat) {
          setFlowPlaying(false);
        }
      },
      assemblyDragObject: playerProcedure.activeAssemblyObject,
      assemblyStartTransform: playerProcedure.activeStep?.startTransform || null,
      assemblyTargetTransform: playerProcedure.activeStep?.endTransform || null,
      assemblyDragEnabled:
        playerProcedure.isAssembly &&
        ["waiting", "dragging"].includes(playerProcedure.status) &&
        Boolean(playerProcedure.activeAssemblyObject),
      assemblyCameraLocked:
        playerProcedure.isAssembly &&
        ["waiting", "dragging"].includes(playerProcedure.status) &&
        Boolean(playerProcedure.activeStep),
      assemblyShowGhost:
        playerProcedure.activeStep?.interaction?.showGhost !== false,
      onAssemblyDragStart: playerProcedure.handleAssemblyDragStart,
      onAssemblyDrag: playerProcedure.handleAssemblyDrag,
      onAssemblyDragEnd: playerProcedure.handleAssemblyDragEnd,
    },

    chapterPanel: {
      freePlay,
      showInfoPanel,
      activeChapter: playerChapter.activeChapter,
      cameraViews: playerChapter.cameraViews,
      activeCameraViewIndex: playerChapter.activeCameraViewIndex,
      selectCameraView: handleSelectChapterCameraView,
      speakChapterDescription: playerSpeech.speakChapterDescription,
      stopSpeaking: playerSpeech.stopSpeaking,
      playChapterAnimations: playerAnimation.playChapterAnimations,
      stopChapterAnimations: playerAnimation.stopChapterAnimations,
      chapterFlowAssignments: getChapterFlowAssignments(
        playerChapter.activeChapter,
      ),
      activeChapterFlowIds,
      playChapterFlow,
      stopChapterFlows,
    },

    animationPanel: {
      animations: playerAnimation.animations,
      selectedAnimations: playerAnimation.selectedAnimations,
      setSelectedAnimations: playerAnimation.setSelectedAnimations,
      setAnimationCommand: playerAnimation.setAnimationCommand,
      stopAnimations: playerAnimation.stopCurrentAnimations,
    },

    flowPanel: {
      flows,
      activeFlow,
      activeFlowId,
      isPlaying: flowPlaying,
      playFlow,
      stopFlow,
    },

    procedurePanel: {
      procedures: playerProcedure.procedures,
      activeProcedure: playerProcedure.activeProcedure,
      activeProcedureId: playerProcedure.activeProcedureId,
      activeStepIndex: playerProcedure.stepIndex,
      completedStepIds: playerProcedure.completedStepIds,
      status: playerProcedure.status,
      feedback: playerProcedure.feedback,
      playProcedure: playerProcedure.playProcedure,
      stopProcedure: playerProcedure.stopProcedure,
      playCompletionAnimation:
        playerProcedure.playProcedureCompletionAnimation,
    },

    toolsMenu: {
      freePlay,
      freePlayMenu,
      cutEnabled,
      toggleCutSection: playerFreePlay.toggleCutSection,
      hideSelectedObject: hideSelectedPlayerObject,
      pullApart: togglePlayerPullApart,
      isPullApartActive: playerFreePlay.isPullApartActive,
      resetAllTransforms: resetAllPlayerView,
      soloSelectedObject: playerFreePlay.soloSelectedObject,
      showAllObjects: playerFreePlay.showAllObjects,
      hideAllObjects,
    },

    cutSlider: {
      freePlay,
      cutEnabled,
      cutAxis,
      setCutAxis: playerFreePlay.updateCutAxis,
      cutValue,
      cutValues,
      cutRanges,
      cutMin,
      cutMax,
      setCutValue,
      updateCutValue: playerFreePlay.updateCutValue,
      resetCutValues: playerFreePlay.resetSection,
      cutAllObjects: playerFreePlay.cutAllObjects,
      setCutAllObjects: playerFreePlay.setCutAllObjects,
      cutTargetAvailable: playerFreePlay.cutTargetAvailable,
    },

    chapterList: {
      freePlay,
      activeMenu,
      material,
      activeChapterId,
      visibleChapters,
      handleSelectChapter,
      clearActiveChapter,
    },

    environmentPanel: {
      viewerSettings,
      setViewerSettings,
      shaderMode: viewerSettings.shaderMode || "original",
      applyShaderMode: applyPlayerShaderMode,
      metalness: viewerSettings.metalness ?? 0.1,
      setMetalness: setPlayerMetalness,
      roughness: viewerSettings.roughness ?? 0.1,
      setRoughness: setPlayerRoughness,
      updateEnvIntensity: updatePlayerEnvIntensity,
    },

    settingsPanel: {
      showAnnotations,
      setShowAnnotations,
      resetView: resetPlayerView,
      resetAll: resetAllPlayerView,
    },

    toolbar: {
      loadPlayerFile: playerProject.loadPlayerFile,
      freePlay,
      setFreePlay,
      setFreePlayMenu,
      setActiveMenu,
      setShowInfoPanel,
      setOutlineObjects,
      stopChapterAnimations: playerAnimation.stopChapterAnimations,
      setCutEnabled,
      showAllObjects: playerFreePlay.showAllObjects,
      resetAllTransforms: resetAllPlayerView,
      activeChapterId,
      handleSelectChapter,
      freePlayMenu,
      activeMenu,
      showInfoPanel,
    },
  };
}
